---
title: "Disnet Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r Pakete laden}
library(igraph)
library(igraphdata)
library(visNetwork)
```

```{r Sonderoptionen da Großes Netzwerk}
#Durch die Größe des Netzwerks können bei Standard-Einstellungen nicht alle Verbindungen dargestellt werden.
#Hierfür wird die maximale Anzahl an Darstellungen erhöht.
options(max.print=999999)
```


```{r Edge- und Nodelist laden}
edges <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/el_fig.csv", header=T, as.is=T, sep=",") #Edgelist wird geladen
nodes <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/nl_fig.csv", header=T, as.is=T, sep = ",") #Nodelist wird geladen
matrix <- as.matrix(edges)#Matrix erstellen
disnet <- graph_from_data_frame(d=matrix, vertices=nodes, directed=FALSE) #Gesamtnetzwerk wird im Dataframe gespeichert


```

```{r Überprüfung der Node-Daten}
V(disnet)$name #Name des jeweiligen Knotens aus der Nodelist
V(disnet)$art # Art des jeweiligen Knotens aus der Nodelist
V(disnet)$prod # Art des jeweiligen Knotens aus der Nodelist
V(disnet)$year # Art des jeweiligen Knotens aus der Nodelist
V(disnet)$income # Art des jeweiligen Knotens aus der Nodelist
```

```{r Ausgabe der Statistiken}
degree(disnet, mode="IN") #Hier lässt sich der Knoten mit den meisten Verbindungen finden


```





```{r Grafische Ausgabe des Gesamtnetzwerks}

E(disnet)$color <- "green"  #as.factor(edges$Type) #Je nach Wert wird die Farbe der Kanten verändert
V(disnet)$shape <- ifelse(nodes$art == 1, "crectangle", ifelse(nodes$art == 2, "circle", "rectangle")) #Die Form der Vertices wird festgelegt Film=square Figur=circle
V(disnet)$color <- as.factor(nodes$art) #Die Farbe der Knoten wird mit unterschiedlichem Wert angepasst
V(disnet)$name <- nodes$name #Die jeweiligen Namen aus der Nodelist werden übernommen
```


```{r Erstellen des ersten Plots}

durchmesser <- layout.fruchterman.reingold(disnet, niter = 50) #zuweisen des Layouts für einfache Skalierbarkeit
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1) #zuweisen der Grundkoordinaten


plot(disnet, 
     vertex.size=5,
     rescale=F,
     layout=durchmesser*1.0) # erste Darstellung des Gesamtnetzwerks


# tkplot(disnet)

```

````{r Attribute anzeigen}
list.vertex.attributes(disnet)
list.edge.attributes(disnet)
```


```{r Teilnetzwerke erstellen}
a1 <- delete.vertices(disnet, V(disnet)[art == 2])
a2 <- delete.vertices(a1, V(a1)[art == 3])
plot(a2)
```

```{r Ego-Netzwerke}

#Mickey Mouse
mickey_ego <- make_ego_graph(disnet, order=1, c("Mickey Mouse"))
plot(mickey_ego[[1]])

#Ralph breaks the Internet
rbthe_ego <- make_ego_graph(disnet, order=1, c("Ralph Breaks the Internet"))
plot(rbthe_ego[[1]])

#Toy Story 4
ts4_ego <- make_ego_graph(disnet, order=2, c("Toy Story 4"))
plot(ts4_ego[[1]])

```



```{r Nur die Disney Figuren (nach Produktionsstudio)}

disnetdeg <- delete.vertices(disnet,which(degree(disnet)<2)) #Hier werden alle 1-fachen und Isolates entfernt
disnetopix <- delete.vertices(disnetdeg, V(disnetdeg)[prod == 3]) #Entfernen der Pixar Figuren
disnetotouch <- delete.vertices(disnetopix, V(disnetopix)[prod == 4]) #Entfernen anderer Figuren
disnetsm <- delete.vertices(disnetsmlg, V(disnetsmlg)[prod == 99]) #Entfernen unbekannter Studios
disnetis <- delete.vertices(disnetsm,which(degree(disnetsm)<2)) #Nochmaliges Entfernen der Isolates



E(disnet)$color <- as.factor(edges$Type) #Je nach Wert wird die Farbe der Kanten verändert
V(disnet)$shape <- ifelse(nodes$prod == 1, "square", "circle") #Die Form der Vertices wird festgelegt Film=square Figur=circle
V(disnet)$color <- as.factor(nodes$art) #Die Farbe der Knoten wird mit unterschiedlichem Wert angepasst

durchmessermin <- layout.kamada.kawai(disnet, niter = 500) #zuweisen des Layouts für einfache Skalierbarkeit
durchmessermin <- norm_coords(durchmessermin, ymin=-1, ymax=1, xmin=-1, xmax=1) #zuweisen der Grundkoordinaten

#Hier wird nur das Netzwerk angezeigt
plot(disnetis, 
     vertex.size=10,
     rescale=F,
     layout=durchmessermin*2.5,
     vertex.size=2,
     vertex.label=NA) # erste Darstellung des Gesamtnetzwerks

#Hier werden die Cluster angezeigt


disnetis2 <- delete.vertices(simplify(disnetis), degree(disnetis)==0)

disnetsmcluster <- cluster_label_prop(disnetis2) # Cluster werden gesucht
class(disnetsmcluster)


plot(disnetsmcluster, disnetis2, vertex.size=10,
     rescale=F,
     layout=durchmessermin*4.5,
     vertex.size=2,
     vertex.label=NA
     )

```



```{r Anzeigen der Figuren aus dem Disney und Pixar-Netzwerk}
# ACHTUNG !!! funktioniert noch nicht so gut!!!!!
disneycluster <- cluster_label_prop(disnet) # Cluster werden gesucht
class(disneycluster)
plot(disneycluster, disnet, layout=layout_with_kk) # erste Darstellung des Gesamtnetzwerks mit Clustern

c <- clusters(disnet)
d <- data.frame(membership=c$membership, prod=V(disnet)$prod, id=1:length(V(disnet)))
c$disprod_members <- aggregate(d$prod=="1", by=list(d$membership), FUN=sum)[,2]
c$pixprod_members <- aggregate(d$prod=="3", by=list(d$membership), FUN=sum)[,2]
V(disnet)$group_has_disprod <- (c$disprod_members[ c$membership ] > 0)
V(disnet)$group_has_pixprod <- (c$pixprod_members[ c$membership ] > 0)

##  Create sub-graphs containing the appropriate membership:
g_mixed <- delete.vertices(disnet, !(V(disnet)$group_has_disprod & V(disnet)$group_has_pixprod))
g_disprod <- delete.vertices(disnet, !(V(disnet)$group_has_disprod & !(V(disnet)$group_has_pixprod)))
g_pixprod <- delete.vertices(disnet, !(V(disnet)$group_has_pixprod & !(V(disnet)$group_has_disprod)))

par(mfrow=c(1,2))
plot(g_disprod, vertex.size=8, vertex.label=nodes$name)
plot(g_mixed, vertex.size=8, vertex.label=nodes$name)
plot(g_pixprod, vertex.size=8, vertex.label=nodes$name)


```



```{r Visnet Baustein aber ohne Nodelist }
# Vorläufige VISNET Darstellung
edges2 <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/el_fig.csv", header=T, as.is=T, sep=",") #Edgelist wird geladen
nodes2 <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/nl_fig.csv", header=T, as.is=T, sep = ",") #Nodelist wird geladen
#visNetwork(nodes, edges, width = "100%")
#Matrix erstellen
matrix2 <- as.matrix(edges2)
disnet2 <- graph_from_data_frame(d=matrix, directed=FALSE)
any(duplicated(colnames(disnet2)))
visIgraph(disnet2, idToLabel = TRUE, layout = "layout_nicely",
  physics = FALSE, smooth = FALSE, type = "square",
  randomSeed = NULL, layoutMatrix = NULL)
```



