---
title: "Disnet Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r Pakete laden}
library(igraph)
library(igraphdata)
library(visNetwork)
```

```{r Sonderoptionen da Großes Netzwerk}
options(max.print=999999)
```


```{r Edge- und Nodelist laden}

edges <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/el_fig.csv", header=T, as.is=T, sep=",") #Edgelist wird geladen

nodes <- read.csv("https://raw.githubusercontent.com/tinomarst/pixar-226305/master/daten/nl.csv", header=T, as.is=T, sep = ",") #Nodelist wird geladen


#visNetwork(nodes, edges, width = "100%")



#Matrix erstellen
matrix <- as.matrix(edges)
disnet <- graph_from_data_frame(d=matrix, vertices=nodes, directed=FALSE)
degree(disnet, mode="IN")

```


```{r Textuelle Ausgabe der Node-Daten}
V(disnet)$name #Name des jeweiligen Knotens aus der Nodelist
V(disnet)$art # Art des jeweiligen Knotens aus der Nodelist
```


```{r Grafische Ausgabe des Gesamtnetzwerks}

E(disnet)$color <- "green"  #as.factor(edges$Type) #Je nach Wert wird die Farbe der Kanten verändert
V(disnet)$shape <- ifelse(nodes$art == 1, "crectangle", ifelse(nodes$art == 2, "circle", "rectangle")) #Die Form der Vertices wird festgelegt Film=square Figur=circle
V(disnet)$color <- as.factor(nodes$art) #Die Farbe der Knoten wird mit unterschiedlichem Wert angepasst
V(disnet)$name <- nodes$name #Die jeweiligen Namen aus der Nodelist werden übernommen
```


```{r Erstellen des ersten Plots}

durchmesser <- layout.fruchterman.reingold(disnet, niter = 50) #zuweisen des Layouts für einfache Skalierbarkeit
durchmesser <- norm_coords(durchmesser, ymin=-1, ymax=1, xmin=-1, xmax=1) #zuweisen der Grundkoordinaten


plot(disnet, 
     vertex.size=5,
     rescale=F,
     layout=durchmesser*1.0) # erste Darstellung des Gesamtnetzwerks

mickey_ego <- make_ego_graph(disnet, order = 1, nodes = V(disnet)$name == "Mickey Mouse", mode="all", mindist=1)

plot(mickey_ego)
```

```{r Teilnetzwerk erstellen}
list.vertex.attributes(disnet)


a1 <- delete.vertices(disnet, V(disnet)[art == 1])
a2 <- delete.vertices(a1, V(a1)[art == 2])
a3 <- delete.vertices(a2, V(a2)[art == 5])
a4 <- delete.vertices(a3, V(a3)[art == 6])
a5 <- delete.vertices(a4, V(a4)[art == 7])
a6 <- delete.vertices(a5, V(a5)[art == 8])
a7 <- delete.vertices(a6, V(a6)[art == 9])
a7

plot(a7)


```


      tkplot(disnet)
      // Tkplot ist eine Ausgabemöglichkeit für eine flexiblere Darstellung

```{r Grafische Ausgabe des Gesamtnetzwerks mit Figuren die mehr als 1 mal vorkommen}

disnetsm <- delete.vertices(disnet,which(degree(disnet)<3))
disnetsm <- delete.vertices(disnet, V(disnet)[prod == 1])
disnetsm <- delete.vertices(disnet, V(disnet)[prod == 2])


E(disnet)$color <- as.factor(edges$Type) #Je nach Wert wird die Farbe der Kanten verändert
V(disnet)$shape <- ifelse(nodes$art == 1, "square", "circle") #Die Form der Vertices wird festgelegt Film=square Figur=circle
V(disnet)$color <- as.factor(nodes$art) #Die Farbe der Knoten wird mit unterschiedlichem Wert angepasst

durchmessermin <- layout.fruchterman.reingold(disnet, niter = 500) #zuweisen des Layouts für einfache Skalierbarkeit
durchmessermin <- norm_coords(durchmessermin, ymin=-1, ymax=1, xmin=-1, xmax=1) #zuweisen der Grundkoordinaten

plot(disnetsm, 
     vertex.size=10,
     rescale=F,
     layout=durchmessermin*0.5) # erste Darstellung des Gesamtnetzwerks
    
```



```{r Zusätzliches Netzwerk mit Clustern}
disneycluster <- cluster_label_prop(disnet) # Cluster werden gesucht
class(disneycluster)
plot(disneycluster, disnet, vertex.size=3,
     rescale=F,
     layout=durchmesser*1.4) # erste Darstellung des Gesamtnetzwerks mit Clustern

```







